GLOBAL_IDX_SETTINGS = {
    "minWordSizefor1Typo": 4,
    "minWordSizefor2Typos": 8,
    "hitsPerPage": 12,
    "paginationLimitedTo": 1000,
    "exactOnSingleWordQuery": "attribute",
    "ranking": [
        "geo",
        "words",
        "filters",
        "proximity",
        "attribute",
        "exact",
        "custom",
        "typo",
    ],
    "removeWordsIfNoResults": "allOptional",
    "queryType": "prefixLast",
    "highlightPreTag": "<mark>",
    "highlightPostTag": "</mark>",
    "alternativesAsExact": ["ignorePlurals", "singleWordSynonym"],
}

PROJECTS_IDX_SETTINGS = {
    **GLOBAL_IDX_SETTINGS,
    "searchableAttributes": [
        "title",
        "unordered(category_title)",
        "unordered(category_code)",
        "unordered(tags)",
        "unordered(team_names)",
        "unordered(supervisor_names)",
        "unordered(description)",
        "unordered(objectID)",
    ],
    "attributesForFaceting": [
        "searchable(category_title)",
        "searchable(category_code)",
        "searchable(tags)",
    ],
    "attributesToHighlight": [
        "title",
        "description",
        "category_title",
        "tags",
        "team_names",
        "supervisor_names",
    ],
    "attributesToSnippet": ["description:20"],
    "attributesToRetrieve": [
        "objectID",
        "title",
        "description",
        "category_title",
        "category_code",
        "project_url",
        "repo_url",
        "page_url",
        "api_url",
        "thumbnail_url",
        "tags",
        "team",
        "supervisors",
        "team_names",
        "supervisor_names",
        "result_url",
    ],
    "disableTypoToleranceOnAttributes": ["objectID", "category_code"],
    "customRanking": ["asc(category_code)", "asc(title)"],
    "renderingContent": {
        "facetOrdering": {
            "facets": {"order": ["category_title", "category_code", "tags"]},
            "values": {
                "category_title": {"sortRemainingBy": "alpha"},
                "category_code": {"sortRemainingBy": "alpha"},
                "tags": {"sortRemainingBy": "count"},
            },
        }
    },
}
